version: '3.7'
services:
  mongodb_container:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - marketplace_data:/var/lib/mongodb

volumes:
  marketplace_data: